=== Yuta2049/03_RD_XML_JSON/ProductData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="productsData" type="productsDataType"/>
  <xs:complexType name="productType">
    <xs:sequence>
      <xs:element name="dateOfManufacture">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="(0[1-9]|[12][0-9]|3[01])[- /.](0[1-9]|1[012])[- /.](19|20)\d\d"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="model">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Z][0-9][0-9][0-9]"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:float" name="price"/>
      <xs:element type="xs:string" name="producer"/>
      <xs:element type="xs:float" name="quantity"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="Color" use="optional"/>
</xs:complexType>
  <xs:complexType name="productsType">
    <xs:sequence>
      <xs:element type="productType" name="product" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="subcategoryType">
    <xs:sequence>
      <xs:element type="productsType" name="products"/>
      <xs:element type="xs:string" name="subcategoryname"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="subcategoriesType">
    <xs:sequence>
      <xs:element type="subcategoryType" name="subcategory" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="categoryType">
    <xs:sequence>
      <xs:element type="xs:string" name="categoryname"/>
      <xs:element type="subcategoriesType" name="subcategories"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="categoriesType">
    <xs:sequence>
      <xs:element type="categoryType" name="category" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="productsDataType">
    <xs:sequence>
      <xs:element type="categoriesType" name="categories"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Yuta2049/03_RD_XML_JSON/ProductData.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<productsData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ProductData.xsd">
    <categories>
        <category>
            <categoryname>CATEGORY 1</categoryname>
            <subcategories>
                <subcategory>
                    <products>
                        <product Color="black">
                            <dateOfManufacture>01-11-2017</dateOfManufacture>
                            <model>AA123</model>
                            <price>200.0</price>
                            <producer>Apple</producer>
                            <quantity>3.0</quantity>
                        </product>
                        <product Color="gold">
                            <dateOfManufacture>01-11-2018</dateOfManufacture>
                            <model>BB345</model>
                            <price>300.0</price>
                            <producer>Apple</producer>
                            <quantity>4.0</quantity>
                        </product>
                    </products>
                    <subcategoryname>SUBCATEGORY 1</subcategoryname>
                </subcategory>
                <subcategory>
                    <products>
                        <product Color="gray">
                            <dateOfManufacture>01-11-2019</dateOfManufacture>
                            <model>CC789</model>
                            <price>500.0</price>
                            <producer>Apple</producer>
                            <quantity>5.0</quantity>
                        </product>
                    </products>
                    <subcategoryname>SUBCATEGORY 2</subcategoryname>
                </subcategory>
            </subcategories>
        </category>
        <category>
            <categoryname>CATEGORY 2</categoryname>
            <subcategories>
                <subcategory>
                    <products>
                        <product Color="black">
                            <dateOfManufacture>01-11-2017</dateOfManufacture>
                            <model>AA123</model>
                            <price>200.0</price>
                            <producer>Apple</producer>
                            <quantity>3.0</quantity>
                        </product>
                        <product Color="gold">
                            <dateOfManufacture>01-11-2018</dateOfManufacture>
                            <model>BB345</model>
                            <price>300.0</price>
                            <producer>Apple</producer>
                            <quantity>4.0</quantity>
                        </product>
                    </products>
                    <subcategoryname>SUBCATEGORY 1</subcategoryname>
                </subcategory>
                <subcategory>
                    <products>
                        <product Color="gray">
                            <dateOfManufacture>01-11-2019</dateOfManufacture>
                            <model>CC789</model>
                            <price>500.0</price>
                            <producer>Apple</producer>
                            <quantity>5.0</quantity>
                        </product>
                    </products>
                    <subcategoryname>SUBCATEGORY 2</subcategoryname>
                </subcategory>
            </subcategories>
        </category>
    </categories>
</productsData>
